### PR TITLE
Implement Google Analytics into website

### PR DESCRIPTION
**Pull request by eirizarry**
This pull request will implement Google Analytics (GA) into the WorldWind website. It is done on this particular site iteration so that we can compare reports for the next site release. 

- The config.yaml file was changed to include the GA tracking ID. 
- A partial template "google_analytics.html" was added and contains the GA script. Line 4 in this file detects the hostname and determines whether or not it's being served in production mode. This will keep GA from running in development. 
- The partial template was then added in the <head> tags of "baseof.html" so that GA will run on every webpage.

### CODE REVIEW

**Review by pdavidc — COMMENTED** [review]
This looks straightforward, though I'm curious why the Google Analytics code appears in Hugo's config and in the new partial.

**Comment by zglueck** [comment]
https://gohugo.io/templates/internal/#google-analytics

**Comment by pdavidc** [comment]
That link doesn't help answer my question. Hugo's docs mention a built-in GA template, which likely uses the config value. But we don't use the built-in template, so it's unclear why we have the config value.

**Comment by eirizarry** [comment]
@pdavidc, you are right--the GA snippet in the config file is not needed. I've tested it, and have removed the code from the config file.

**Comment by eirizarry** [comment]
Final changes for implementing GA: 

We are now using the GA code in the config file, and we are also using Hugo's internal GA template so that we do not have to create our own. As for excluding analytics during development, I have created a filter on the GA account which excludes localhost--this appears to be working as it should.

**Review by pdavidc — APPROVED** [review]
Very simple and clean. Nice!

**Pull request merged**
