### PR TITLE
Add OmnidirectionalSightline Example and Tutorial pages and images

### PR DESCRIPTION
**Pull request by zglueck**

### CODE REVIEW

**Review by pdavidc — CHANGES_REQUESTED** [review]
Let's use an animated image at the top of this tutorial. @PJHogan needs screen shots to demonstrate the capability. An animated screen shot embedded in the tutorial would go a long way.

**Comment by zglueck** [comment]
@pdavidc good call, I've added a short video demonstrating the line of sight. There was a bit of balancing act between quality/length/size

**Comment by pdavidc** [comment]
The video works but it needs adjustment. The video's dimensions and aspect ratio don't work well in that space, and the size on disk is still significant.

@eirizarry Would you please take a look at this with @zglueck and offer your insights.

**Comment by pdavidc** [comment]
The webm based video is great. If you can provide a fallback for Safari and IE, we can deploy this.

**Comment by zglueck** [comment]
@pdavidc @eirizarry I changed the gif to webm; however, in Chrome I get some weird effects while viewing the video. I ripped from mp4 to webm again with the same results. The video shows fine in Firefox and now it looks like Safari doesn't support webm yet (which also means iOS).

So, @eirizarry, what do  you think of a youtube video? Hugo has built-in shortcode support for youtube. Let me know what direction you want to go.

**Comment by eirizarry** [comment]
Just tested all the browsers on my end. A YouTube video would be great so that this tutorial is compatible for all browsers. Does WorldWind have it's own channel tutorials/examples? 

Also, as a side note, I noticed the this tutorial comes under three different names. It is "OmnidirectionalSightlineFragment" in WWA's repo, "Line of Sight" on the tutorials page, and "Movable Line of Sight" on the examples page. I think it would be a good idea to have these all under the same name. If you agree, I will make those changes after we set the video how we want it, as well as a content check for sizing/spacing on the web page.

**Comment by zglueck** [comment]
I suggest we go with the youtube option for the following reasons:

1. Compatibility - should work in nearly everything
2. Content Delivery - the Hugo shortcode adds an iframe with youtubes url, which takes hosting out of our hands
3. Ease of Use - both now and as we add new features and want showcase them we can add them to youtube

**Comment by pdavidc** [comment]
@zglueck I agree with your reasoning, and it looks like @eirizarry does as well.

@eirizarry WorldWind may have a YouTube channel, but we haven't created one that I'm aware of. Let me know what you find, and what's involved with creating a channel. Also, standardizing the example and tutorial names sounds good.

**Comment by eirizarry** [comment]
I have created a NASA WorldWind brand account, to which I can add users and assign ownership. We can use this account to upload our YouTube videos.

**Comment by zglueck** [comment]
I've updated the pull request to use the youtube video. @eirizarry I didn't make changes to the naming.

**Comment by eirizarry** [comment]
Question: since we've embedded a video of what view the code provides, is it necessary to include the image at the bottom of the screen for this tutorial?

**Comment by zglueck** [comment]
@pdavidc how does this look?

**Comment by pdavidc** [comment]
This looks great to me. I'll approve the changes, and either of you can merge when you're ready.

**Review by pdavidc — APPROVED** [review]

**Pull request merged**
