### PR TITLE
Initial WebStorm project

### LINKED ISSUE #59: Hugo site WebStorm project
Establish a WebStorm project for the new Hugo based site.

### PR DESCRIPTION
**Pull request by pdavidc**
- Shared WebStorm project files under the .idea folder
- npm project configuration file (package.json) to execute Hugo tasks in WebStorm
- .gitignore entries to suppress local WebStorm project files and Hugo build output
- Closes #59

### CODE REVIEW

**Comment by zglueck** [comment]
The hugo serve startup functionality is nice.

Do you want to apply html formatting rules to all of the layout files?

**Comment by pdavidc** [comment]
That's a good idea. Could you handle establishing the html formatting rules?

**Comment by zglueck** [comment]
@pdavidc there are some nuances to the code formatting and golang template characters which impede a positive workflow integration of WebStorm formatting.

Specifically, I haven't been able to get the code formatter to respect indentations with golang template curly braces.

For Example, the current `single.html` template:
```html
{{ define "head-title" }}
    NASA WorldWind - {{ .Params.Title }}   
{{ end }}
{{ define "main-block" }}
    <div class="container">
        {{ .Content }}
    </div>
{{ end }}
```
Becomes:
```html
{{ define "head-title" }}
NASA WorldWind - {{ .Params.Title }}
{{ end }}
{{ define "main-block" }}
<div class="container">
    {{ .Content }}
</div>
{{ end }}
```

The indentation of the `{{` content helps communicate the layout of the file. For now, I suggest we back burner the automatic code formatting until we have a little more time to integrate the golang template characters and spacing better.

**Review by zglueck — APPROVED** [review]
Nice integration with WebStorm, the automatic startup of the `hugo serve` functionality is very helpful.

**Comment by pdavidc** [comment]
@zglueck Thanks for the review and careful consideration of WebStorm auto code formatting. 

I agree with your conclusion regarding formatting. Auto formatting for website code is a low priority. Additionally, if the IDE cannot format Hugo's mixed content Markdown and HTML in a manner that's good enough, we certainly won't use it.

**Pull request merged**
