### PR TITLE
Feature/#10 develop site infrastructure

### LINKED ISSUE #10: Develop templates/blocks/partials for content
Implement the site generator, and required directory/file structure to meet the needs of #9. This would be the common site initialization, configuration, and setup provided by the site generator.

### PR DESCRIPTION
**Pull request by zglueck**
This closes #10 by initializing the Hugo project and specifying some default html templates.

[Hugo uses golang's html template engine](https://gohugo.io/templates/overview/). I've defined a `baseof.html` [block template](https://gohugo.io/templates/blocks/) which all other full page templates utilize. The `list.html` and `single.html` are the default templates used by Hugo for most pages. The `project.html` template is similar to `single.html`, except that it adds the [partial template](https://gohugo.io/templates/partials/) `project-navbar.html` which adds project specific pages to a page.

The css framework is Bootstrap with a free, CDN hosted theme [Spacelab](https://bootswatch.com/spacelab/). There is a `theme.css` extension in the `static/css` directory which provides some additional functionality.

This pr also includes the `_index.md` file in the Android project content directory. The actual content isn't there, but this will allow you to visualize the site locally. Just: `hugo serve` and navigate to the [Android Project](http://localhost:1313/android/). Since the `_index.md` file is the only content file, the http://localhost:1313/android/ is the only page that will work.

### CODE REVIEW

**Review by pdavidc — CHANGES_REQUESTED** [review]
This looks great. There are three minor changes I think are worthwhile:

1. Replace "World Wind" with "WorldWind". This is a recent change, so it's no surprise that it didn't make it into your earlier draft.

2. Adjust the list template conditional. After some consideration I think it's odd that tutorials is the default list case. Could tutorials be treated as another special case like mainpage and projectpage, with the default case displaying simple undecorated content?

3. In the list template, is the TutorialName property necessary, or could the Title property work just as well?

**Comment by zglueck** [comment]
I was going to make the World Wind -> WorldWind changes for this pull request but refrained. It would have pulled in the README and LICENSE.html, and I didn't want to distract from the content of this pr. If it isn't a big deal I can add the name change in, otherwise, I'll open an additional PR later to change all the names.

Great idea on the default case. Having an obvious default would help when we add new content somewhere and don't get the anticipated result. I will add an additional key/value pair to the front matter to indicate whether the item is a tutorial list.

Title property is an option. In the mock up sites, the title typically carried the properly formatted project name, which doesn't really describe the content. Now would be a good time to think about the use pattern and spell something out, either in the default archetypes or in the READEME, or both. I will spend a little time coming up with an easy to follow convention and include it in the other updates.

**Comment by pdavidc** [comment]
Thanks, @zglueck.

Let's make the World Wind -> WorldWind name change whenever we can. It's okay that the README and LICENSE aren't consistent at the moment.

We'll look forward to what you come up with for the tutorial key/value pair and the Title property. The comment about Title vs TutorialName was an observation, so if a separate property is best please disregard.

**Comment by zglueck** [comment]
@pdavidc for number 2 and 3 I decided to opt for a more generic template. This will prevent us from constantly editing the list template as new list content is generated. Instead of the `tutorialTitle` the list template uses the `title` property and for the description `listdescription` property.

To facilitate content addition I extended the `default.md` archetype for each project. The project specific archetype populates the `slug` and `projectname` properties.

I also refactored how the `<title></title>` element is populated to better reflect when the page is in a project space.

**Review by pdavidc — APPROVED** [review]

**Comment by pdavidc** [comment]
That adjustment sounds like a much better design for list content. Nice work!

**Pull request merged**
